/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1306190045_zeyneptemizel;

import java.io.IOException;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static pkg1306190045_zeyneptemizel.MusteriIcerik.sq;

/**
 *
 * @author zeyne
 */
public class Calisan extends javax.swing.JFrame {
    Connection con=null;
    PreparedStatement pst=null;
    /**
     * Creates new form Calisan
     */
    public Calisan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bakiye = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bakiye_buton = new javax.swing.JButton();
        acil = new javax.swing.JButton();
        davut = new javax.swing.JToggleButton();
        kredi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(768, 650));
        setSize(new java.awt.Dimension(768, 650));
        getContentPane().setLayout(null);

        bakiye.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(bakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(490, 310, 280, 30);

        jButton1.setText("geri dön");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 10, 71, 23);

        bakiye_buton.setBackground(new java.awt.Color(102, 102, 102));
        bakiye_buton.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        bakiye_buton.setText("BAKİYE ÖĞREN");
        bakiye_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakiye_butonActionPerformed(evt);
            }
        });
        getContentPane().add(bakiye_buton);
        bakiye_buton.setBounds(490, 250, 280, 60);

        acil.setBackground(new java.awt.Color(102, 102, 102));
        acil.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        acil.setText("ACİL DURUM PROTOKOLİ");
        acil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acilActionPerformed(evt);
            }
        });
        getContentPane().add(acil);
        acil.setBounds(490, 140, 280, 90);

        davut.setText(":)");
        davut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                davutActionPerformed(evt);
            }
        });
        getContentPane().add(davut);
        davut.setBounds(20, 260, 41, 23);

        kredi.setBackground(new java.awt.Color(102, 102, 102));
        kredi.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        kredi.setText("BEKLEYEN KREDİ ONAYLARI");
        kredi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krediActionPerformed(evt);
            }
        });
        getContentPane().add(kredi);
        kredi.setBounds(0, 140, 280, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 770, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void krediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krediActionPerformed
        try {  
            new sqlcalisan().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Calisan.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_krediActionPerformed

    private void acilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acilActionPerformed
 String message = "ACİL DURUM PROTOKOLİ BAŞLATMA BAŞARILI \n PARA GÖNDERME İŞLEMLERİ DURDURULDU. \n PARA ÇEKME İŞLEMLERİ DURDURULDU. \n TÜM KASALAR KİLİTLENDİ. \n NAKLİYE ARAÇLARINA ÇAĞRI GÖNDERİLDİ. \n ÜST DÜZEY YÖNETİCİLER ADP TOPLANTISI \n İÇİN SİZİ BEKLİYOR EFENDİM.";

        Console c=new Console() {};
        try {
            c.a();
        } catch (IOException ex) {
            Logger.getLogger(Calisan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Calisan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Calisan.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Calisan.class.getName()).log(Level.SEVERE, null, ex);
        }
        ADP a = new ADP();
        a.setVisible(true);
        a.slowPrint(message);
        
    }//GEN-LAST:event_acilActionPerformed

    private void bakiye_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakiye_butonActionPerformed
        String stringName = "sifre";
        String query= "SELECT * FROM logintable WHERE username= '" + stringName + "'";
        try 
        {
            con=DriverManager.getConnection("jdbc:derby://localhost:1527/logindb","login","login" );
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);
           while(rs.next()){
           Integer value = rs.getInt(5);
           bakiye.setText(value.toString());
        }
        }catch (SQLException e ) 
        {
            e.printStackTrace();
        } 
    }//GEN-LAST:event_bakiye_butonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new Banka().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void davutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_davutActionPerformed
JOptionPane.showMessageDialog(null, "HOCAM SON LAB DERSİNDE ÖDEV VEREMEYECEĞİNİZİ ÖĞRENİNCE ÇOK ÜZÜLMÜŞTÜNÜZ SİZE KIYAMADIK :((((( \n EMEKLERİNİZ İÇİN TEŞEKKÜRLER");        // TODO add your handling code here:
    }//GEN-LAST:event_davutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calisan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calisan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calisan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calisan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calisan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acil;
    private javax.swing.JLabel bakiye;
    private javax.swing.JButton bakiye_buton;
    private javax.swing.JToggleButton davut;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kredi;
    // End of variables declaration//GEN-END:variables
}
