/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1306190045_zeyneptemizel;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static pkg1306190045_zeyneptemizel.Musteri.k_ad;
import static pkg1306190045_zeyneptemizel.Musteri.username;

/**
 *
 * @author zeyne
 */
public class KrediIslemler extends javax.swing.JFrame implements Fonksiyonlar.Kapa,Fonksiyonlar.sql {
    
     @Override
     public void kapa(){
    this.dispose();
    }
   @Override
   public Connection connectdb()
   {
    Connection con=null;
        try {
            con=DriverManager.getConnection("jdbc:derby://localhost:1527/logindb","login","login");
            return con;
        } catch (SQLException ex) {
        }
        return null;
    }
   Connection con=connectdb();
   PreparedStatement ps=null;
   ResultSet rs=null;

    /**
     * Creates new form KrediIslemler
     */
    public KrediIslemler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kredi_talep = new javax.swing.JButton();
        kredi_limit = new javax.swing.JButton();
        kredi_miktar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        limit_miktar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(212, 175, 55));

        kredi_talep.setBackground(new java.awt.Color(104, 58, 107));
        kredi_talep.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kredi_talep.setText("KREDİ BAŞVURUSU");
        kredi_talep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kredi_talepActionPerformed(evt);
            }
        });

        kredi_limit.setBackground(new java.awt.Color(104, 58, 107));
        kredi_limit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kredi_limit.setText("LİMİT DEĞİŞTİRME");
        kredi_limit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kredi_limitActionPerformed(evt);
            }
        });

        jLabel1.setText("istediğiniz miktar");

        jLabel4.setText("istediğiniz miktar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kredi_talep, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(kredi_limit, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kredi_miktar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                        .addComponent(limit_miktar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kredi_miktar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limit_miktar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kredi_talep, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kredi_limit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kredi_limitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kredi_limitActionPerformed
        Musteri musteri = new Musteri();
        String u_name = musteri.getMusteri();
                

        
        
        String query= "UPDATE logintable SET KREDI_LIMIT=" +limit_miktar.getText() + " WHERE username='" + u_name + "'";

         try 
        {
            Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/logindb","login","login" );
            Statement stmt1 = con.createStatement();
            stmt1.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Kredi limitiniz başarılı bir şekilde değiştirildi.");

            dispose();
        
        }
       
     catch (SQLException ex) {
            Logger.getLogger(MusteriIcerik.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_kredi_limitActionPerformed

    private void kredi_talepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kredi_talepActionPerformed
Musteri musteri = new Musteri();
        String u_name = musteri.getMusteri();
        
        String query= "UPDATE logintable SET KREDI_MIKTAR=" +kredi_miktar.getText() + " WHERE username='" + u_name + "'";
       String query3= "INSERT into kredi VALUES (?,?)";

        String query2= "UPDATE kredi SET KREDI_MIKTAR=" +kredi_miktar.getText() + " WHERE username='" + u_name + "'";

         try 
        {
            Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/logindb","login","login" );
            PreparedStatement  pst=con.prepareStatement(query3);
            pst.setString(1,u_name);      
            pst.setString(2,kredi_miktar.getText());
            Statement stmt1 = con.createStatement();
            stmt1.executeUpdate(query);
            stmt1.executeUpdate(query2);
            JOptionPane.showMessageDialog(null, "Başarılı. Krediniz onaylandıktan sonra bankamıza uğrayarak işlemlerinizi halledebilirsiniz.");
            dispose();
        
        }
       
     catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "BAŞARISIZ");
            Logger.getLogger(MusteriIcerik.class.getName()).log(Level.SEVERE, null, ex);
        }    }//GEN-LAST:event_kredi_talepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KrediIslemler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KrediIslemler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KrediIslemler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KrediIslemler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KrediIslemler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kredi_limit;
    private javax.swing.JTextField kredi_miktar;
    private javax.swing.JButton kredi_talep;
    private javax.swing.JTextField limit_miktar;
    // End of variables declaration//GEN-END:variables
}
