/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1306190045_zeyneptemizel;

import static java.lang.String.valueOf;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author zeyne
 */
public class MusteriIcerik extends javax.swing.JFrame {
   
static sqltables sq = null;

    /**
     * Creates new form MusteriIcerik
     */
    public MusteriIcerik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        para_yatir = new javax.swing.JButton();
        fatura = new javax.swing.JButton();
        para_gonder = new javax.swing.JButton();
        kredi = new javax.swing.JButton();
        cikis = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        bakiye_ogren = new javax.swing.JButton();
        para_cek = new javax.swing.JButton();
        bakiye = new javax.swing.JLabel();
        cek_yatir = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        krediniz = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        limitiniz = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(212, 175, 55));

        para_yatir.setBackground(new java.awt.Color(212, 175, 55));
        para_yatir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        para_yatir.setText("PARA YATIR");
        para_yatir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                para_yatirActionPerformed(evt);
            }
        });

        fatura.setBackground(new java.awt.Color(212, 175, 55));
        fatura.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fatura.setText("FATURA İŞLEMLERİ");
        fatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faturaActionPerformed(evt);
            }
        });

        para_gonder.setBackground(new java.awt.Color(212, 175, 55));
        para_gonder.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        para_gonder.setText("PARA GÖNDER");
        para_gonder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                para_gonderActionPerformed(evt);
            }
        });

        kredi.setBackground(new java.awt.Color(212, 175, 55));
        kredi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        kredi.setText("KREDİ KARTI İŞLEMLERİ");
        kredi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krediActionPerformed(evt);
            }
        });

        cikis.setBackground(new java.awt.Color(212, 175, 55));
        cikis.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cikis.setText("ÇIKIŞ YAP");
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(104, 58, 107));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setText("Zeynep Temizel ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setText("1306190045 ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Nesneye Yönelik Programlama");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("şifreyi bulamadıysanız şifre 666");

        jToggleButton1.setBackground(new java.awt.Color(104, 58, 107));
        jToggleButton1.setText("ANA MENÜYE DÖN");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(107, 107, 107))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(80, 80, 80)
                .addComponent(jLabel9)
                .addGap(28, 28, 28)
                .addComponent(jLabel10)
                .addGap(28, 28, 28)
                .addComponent(jLabel11)
                .addContainerGap(334, Short.MAX_VALUE))
        );

        bakiye_ogren.setBackground(new java.awt.Color(212, 175, 55));
        bakiye_ogren.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bakiye_ogren.setText("BAKİYE ÖĞREN");
        bakiye_ogren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakiye_ogrenActionPerformed(evt);
            }
        });

        para_cek.setBackground(new java.awt.Color(212, 175, 55));
        para_cek.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        para_cek.setText("PARA ÇEK");
        para_cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                para_cekActionPerformed(evt);
            }
        });

        bakiye.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        cek_yatir.setBackground(new java.awt.Color(212, 175, 55));
        cek_yatir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cek_yatirActionPerformed(evt);
            }
        });

        jLabel1.setText("ÇEKMEK VEYA YATIRMAK İSTEDİĞİNİ PARAYA GİRİP İŞLEME BASINIZ");

        jLabel3.setText("BAKİYENİZ");

        jLabel5.setText("KREDİNİZ");

        krediniz.setBackground(new java.awt.Color(212, 175, 55));
        krediniz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kredinizActionPerformed(evt);
            }
        });

        jLabel4.setText("KART LİMİTİNİZ");

        limitiniz.setBackground(new java.awt.Color(212, 175, 55));
        limitiniz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limitinizActionPerformed(evt);
            }
        });

        jLabel6.setText("BİLGİLERİ GÜNCELLEMEK İÇİN BAKİYE ÖĞRENE BASINIZ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cikis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(para_cek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(para_yatir, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
                                .addGap(83, 83, 83)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(kredi, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(para_gonder, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bakiye_ogren, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(fatura, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cek_yatir, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(38, 38, 38)
                                .addComponent(krediniz, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(limitiniz, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cek_yatir, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(krediniz, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limitiniz, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(59, 59, 59)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fatura, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bakiye_ogren, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(para_gonder, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(para_cek, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(para_yatir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kredi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cikis, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1206, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 609, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 609, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 429, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 430, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cek_yatirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cek_yatirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cek_yatirActionPerformed

    private void para_cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_para_cekActionPerformed
        JOptionPane.showMessageDialog(null, "Hesabınızdaki paradan fazlasını çekmeye kalkışmayın. Tabii bankamıza borçlanmak istemiyorsanız :)");
        String para_eksilen;

        int suanki_para = 0;
        Musteri musteri = new Musteri();
        String u_name = musteri.getMusteri();

        String query= "SELECT money FROM logintable WHERE username= '" + u_name + "'";
        try
        {
            Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/logindb","login","login" );
            para_eksilen = cek_yatir.getText();
            Integer para_eksilen_int;
            para_eksilen_int = Integer.valueOf(para_eksilen);

            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next()){
                suanki_para = rs.getInt(1);
            }

            int guncel_para = suanki_para - para_eksilen_int;
            String query2= "UPDATE logintable SET money=" +guncel_para + " WHERE username='" + u_name + "'";

            stmt.executeUpdate(query2);

        } catch (SQLException ex) {
            Logger.getLogger(MusteriIcerik.class.getName()).log(Level.SEVERE, null, ex);
        }
         Harac hrc = new Harac();
        hrc.method();

    }//GEN-LAST:event_para_cekActionPerformed
public static JTextField getlimit(){
return limitiniz;
}
    private void bakiye_ogrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakiye_ogrenActionPerformed

        Musteri musteri = new Musteri();
        String u_name = musteri.getMusteri();

        String query= "SELECT * FROM logintable WHERE username= '" + u_name + "'";
        String t = "Krediniz henüz onaylanmamıştır. İşleminizi hızlandırmak için bankamıza uğrayabilirsiniz.";

        try
        {
            Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/logindb","login","login" );
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next()){
                Integer value = rs.getInt(5);
                bakiye.setText(value.toString());
                boolean kredibool = rs.getBoolean(7);
                int boolint =rs.getInt(8);
                Integer limit = rs.getInt(6);
                limitiniz.setText(limit.toString());
                if (boolint !=0){
                if(kredibool == true){
                Integer kredi= rs.getInt(8);
                krediniz.setText(kredi.toString()+ " değerindeki krediniz onaylanmıştır. Bankamıza başvurarak temin edebilirsiniz.");
            }
                else krediniz.setText(t);
            }
            }
        }catch (SQLException e )
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bakiye_ogrenActionPerformed

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisActionPerformed
System.exit(0);
dispose();    }//GEN-LAST:event_cikisActionPerformed

    private void krediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krediActionPerformed
new KrediIslemler().setVisible(true);

    }//GEN-LAST:event_krediActionPerformed

    private void para_gonderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_para_gonderActionPerformed
        JOptionPane.showMessageDialog(null, "Sadece ailemizdeki kişilere para gönderebilirsiniz.");
        new ParaGonder().setVisible(true);
        try {
            sq = new sqltables();
        } catch (SQLException ex) {
            Logger.getLogger(MusteriIcerik.class.getName()).log(Level.SEVERE, null, ex);
        }
        sq.setVisible(true);
         Harac hrc = new Harac();
        hrc.method();

    }//GEN-LAST:event_para_gonderActionPerformed

    private void faturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faturaActionPerformed
new Fatura().setVisible(true);    }//GEN-LAST:event_faturaActionPerformed

    private void para_yatirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_para_yatirActionPerformed
        JOptionPane.showMessageDialog(null, "Bankamız hizmetlerinize minnattar :)");
        String para_eklenen;
        int suanki_para = 0;

        Musteri musteri = new Musteri();
        String u_name = musteri.getMusteri();

        String query= "SELECT money FROM logintable WHERE username= '" + u_name + "'";
        try
        {
            Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/logindb","login","login" );
            para_eklenen = cek_yatir.getText();
            int para_eksilen_int = Integer.valueOf(para_eklenen);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next()){
                suanki_para = rs.getInt(1);
            }
            int guncel_para = suanki_para + para_eksilen_int;
            String query2= "UPDATE logintable SET money=" +guncel_para + " WHERE username='" + u_name + "'";

            stmt.executeUpdate(query2);

        } catch (SQLException ex) {
            Logger.getLogger(MusteriIcerik.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_para_yatirActionPerformed

    private void kredinizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kredinizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kredinizActionPerformed

    private void limitinizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limitinizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limitinizActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        dispose();
        new Banka().setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusteriIcerik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusteriIcerik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusteriIcerik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusteriIcerik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusteriIcerik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bakiye;
    private javax.swing.JButton bakiye_ogren;
    private javax.swing.JTextField cek_yatir;
    private javax.swing.JButton cikis;
    private javax.swing.JButton fatura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton kredi;
    private javax.swing.JTextField krediniz;
    public static javax.swing.JTextField limitiniz;
    private javax.swing.JButton para_cek;
    private javax.swing.JButton para_gonder;
    private javax.swing.JButton para_yatir;
    // End of variables declaration//GEN-END:variables
}
