/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1306190045_zeyneptemizel;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pkg1306190045_zeyneptemizel.Fonksiyonlar.sql;
import static pkg1306190045_zeyneptemizel.Musteri.username;
import static pkg1306190045_zeyneptemizel.MusteriIcerik.sq;

/**
 *
 * @author zeyne
 */
public  class ParaGonder extends javax.swing.JFrame implements sql {
     public Connection connectdb()
   {
    Connection con=null;
        try {
            con=DriverManager.getConnection("jdbc:derby://localhost:1527/logindb","login","login");
            return con;
        } catch (SQLException ex) {
        }
        return null;
    }
    public static String username2;
    public static String goingmoney;
   Connection con=connectdb();
   PreparedStatement ps=null;
   ResultSet rs=null;

    /**
     * Creates new form ParaGonder
     */
    public ParaGonder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        name = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        money = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(500, 0));

        name.setColumns(20);
        name.setRows(5);
        jScrollPane1.setViewportView(name);

        jLabel1.setText("yandaki tablodan seçtiğiniz kişinin adını yazınız.");

        money.setColumns(20);
        money.setRows(5);
        jScrollPane2.setViewportView(money);

        jLabel2.setText("göndermek istediğiniz parayı girin.");

        jButton1.setText("GÖNDER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(85, 85, 85))))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            username2 = name.getText();
            goingmoney = money.getText();
            Integer goingmoney_int = Integer.valueOf(goingmoney);
            int suanki_para2 = 0;
            int suanki_para =0;
            String query= "SELECT money FROM logintable WHERE username= '" + username2 + "'";             
            String query2= "SELECT money FROM logintable WHERE username= '" + username + "'";
     try 
        {
            Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/logindb","login","login" );
            
            
            Statement stmt1 = con.createStatement();
            ResultSet rs1 = stmt1.executeQuery(query2);
            while(rs1.next()){
            suanki_para = rs1.getInt(1);
        } 
        int guncel_para = suanki_para - goingmoney_int;
        String query4= "UPDATE logintable SET money=" +guncel_para + " WHERE username='" + username + "'";
        stmt1.executeUpdate(query4);

        
        }
     
     
     catch (SQLException ex) {
            Logger.getLogger(MusteriIcerik.class.getName()).log(Level.SEVERE, null, ex);
        }
     
     try 
        {
            Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/logindb","login","login" );
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next()){
             suanki_para2 = rs.getInt(1);
        }
        int guncel_para2 = suanki_para2 +goingmoney_int;
        String query3= "UPDATE logintable SET money=" +guncel_para2 + " WHERE username='" + username2 + "'";
        stmt.executeUpdate(query3);

        } catch (SQLException ex) {
            Logger.getLogger(MusteriIcerik.class.getName()).log(Level.SEVERE, null, ex);
        }

        dispose();
        sq.dispose();
        
        Harac hrc = new Harac();
        hrc.method();
        
        
        
            }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParaGonder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParaGonder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParaGonder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParaGonder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParaGonder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea money;
    private javax.swing.JTextArea name;
    // End of variables declaration//GEN-END:variables
}
